ASPFamilyRelations/Controllers/HomeController.cs
using DataAccess.Entities;
using Services.BuisnessLogic.Base;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace ASPFamilyRelations.Controllers
{
    public class HomeController : Controller
    {
        IRelationService relationService = null;
        IPersonService personService = null;

        public HomeController(IRelationService relationService, IPersonService personService)
        {
            this.relationService = relationService;
            this.personService = personService;
        }

        public ActionResult Index()
        {
            IEnumerable<Person> persons = personService.GetPersons();

            return View(persons);
        }

        public ActionResult ShowFiltered(string surname, string name, string patronymic, 
            string birthDate, string country, string city, string street)
        {
            string[] keywords = { surname, name, patronymic, country, city, street };

            DateTime birth;

            bool hasDate = DateTime.TryParse(birthDate, out birth);

            Expression<Func<Person, bool>> func;

            if (hasDate)
                func = x => x.BirthDate == birth;
            else
                func = x => true;

            IEnumerable<Person> persons = personService.SearchByString(func, keywords);

            return View("Index", persons);
        }

        public ActionResult GetRelations(int id)
        {
            ViewBag.Person = personService.GetPerson(id);

            IEnumerable<Relation> relations = relationService.GetRelations(x=>x.SourceId==id);

            return View(relations);
        }

        public PartialViewResult Edit(int id, bool details = false)
        {
            ViewBag.Details = details;

            return PartialView("Modal/_Edit", id);
        }

        public PartialViewResult GetPerson(int id)
        {
            var person = personService.GetPerson(id);

            return PartialView("Modal/_PersonPartial", person);
        }

        public PartialViewResult GetPersonDetails(int id)
        {
            var person = personService.GetPerson(id);

            return PartialView("Modal/_PersonDetailsPartial", person);
        }

        [HttpPost]
        public ActionResult UpdatePerson(Person person)
        {
            if (ModelState.IsValid)
            {
                if (person.Id == 0)
                {
                    personService.AddPerson(person);
                }

                personService.UpdatePerson(person);

                ViewBag.Message = "Изменения профиля были сохранены";

            }
            return PartialView("Modal/_PersonPartial", person);
        }

        [HttpPost]
        public ActionResult AddPerson([Bind(Exclude = "Id")]Person person)
        {
            return UpdatePerson(person);
        }

        [HttpPost]
        public JsonResult RemovePerson(int id)
        {
            personService.RemovePerson(id);

            return Json(new { IsRemoved = true }, JsonRequestBehavior.AllowGet);
        }
 
    }
}

ASPFamilyRelations/Controllers/RelationController.cs
using DataAccess.Entities;
using Services.BuisnessLogic.Base;
using System.Linq;
using System.Web.Mvc;

namespace ASPFamilyRelations.Controllers
{
    public class RelationController : Controller
    {
        IRelationService relationService = null;
        IRelationNameService relationNameService = null;
        IPersonService personService = null;

        public RelationController(IRelationService relationService, 
            IRelationNameService relationNameService, IPersonService personService)
        {
            this.relationService = relationService;
            this.relationNameService = relationNameService;
            this.personService = personService;
        }

        // GET: Relation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult RemoveRelation(int id)
        {
            bool removed = relationService.RemoveRelation(id);

            return Json(new { IsRemoved = removed }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult Edit(int id, int sourceId=0)
        {
            ViewBag.SourceId = sourceId;

            return PartialView("Modal/_Edit", id);
        }

        public PartialViewResult GetRelation(int id)
        {
            var relation = relationService.GetRelation(id);

            ViewBag.Person = personService.GetPerson(relation.SourceId).ToString();

            ViewBag.RelationNames = relationNameService.GetRelationNames().Select(x => x.Name).ToArray();

            return PartialView("Modal/_RelationPartial", relation);
        }

        public PartialViewResult NewRelation(int sourceId)
        {
            Relation relation = new Relation() { SourceId = sourceId };

            ViewBag.Person = personService.GetPerson(sourceId).ToString();

            ViewBag.RelationNames = relationNameService.GetRelationNames().Select(x => x.Name).ToArray();

            ViewBag.Persons = personService.GetPersons(x=>x.Id!= sourceId).ToArray();

            return PartialView("Modal/_NewRelationPartial", relation);
        }

        [HttpPost]
        public ActionResult UpdateRelation(Relation relation)
        {
            ViewBag.Person = personService.GetPerson(relation.SourceId).ToString();

            ViewBag.RelationNames = relationNameService.GetRelationNames().Select(x => x.Name).ToArray();

            if (relation.Id == 0)
            {
                relationService.AddRelation(relation);
            }

            else
            {
                relationService.UpdateRelation(relation);
            }

            ViewBag.Message = "Изменения родства были сохранены";

            relation.TargetPerson = personService.GetPerson(relation.TargetId);

            return PartialView("Modal/_RelationPartial", relation);
        }

        [HttpPost]
        public ActionResult AddRelation([Bind(Exclude = "Id")]Relation relation)
        {
            return UpdateRelation(relation);
        }
    }
}

ASPFamilyRelations/Views/Home/GetRelations.cshtml
@model IEnumerable<DataAccess.Entities.Relation>

@{
    ViewBag.Title = "Родственники";
}


<h3>@ViewBag.Person.ToString() : родственники</h3>

@if (Model.Count() != 0)
{
    <table class="table table-bordered table-hover">
        <tr>
            <th>№</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Кто ему</th>
            <th>Действие</th>
        </tr>
        @foreach (var line in Model)
        {
            <tr>
                <td>@line.Id</td>
                <td>@line.TargetPerson.Surname</td>
                <td>@line.TargetPerson.Name</td>
                <td>@line.TargetPerson.Patronymic</td>
                <td>@line.RelationName.MirrorName</td>
                <td>
                    <button class="btn btn-xs btn-warning" title="Карточка родственника" onclick="showDetailsModal(@line.TargetId)">
                        <i class="glyphicon glyphicon-zoom-in"></i>
                    </button>
                    <button class="btn btn-xs btn-warning" title="Редактировать родство" onclick="showUpdateRelationModal(@line.Id,0)">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </button>
                    <button class="btn btn-xs btn-danger" title="Удалить родство" onclick="removeRelation(@line.Id)">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </td>
            </tr>
        }
    </table>
}
else
{
    <h4>База данных пуста</h4>
}

<button class="btn btn-default" title="Добавить родственника" onclick="showUpdateRelationModal(0, @ViewBag.Person.Id)">
    <i class="glyphicon glyphicon-plus"></i>
</button>

<button class="hidden" id="submitBtn" data-toggle="modal" data-target="#myModal"></button>
<div id="modal-content">
</div>

@section Scripts{
<script type="text/javascript">
        function showDetailsModal(id) {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("Edit", "Home")' + '?id=' + id + '&details=true',
                success: function (partialView) {
                    $('#modal-content').empty().html(partialView);
                    $('#submitBtn').click();
            },
            error: function(err){
                console.log(err);
            }
            });
        }

        function showUpdateRelationModal(id, sourceId) {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("Edit", "Relation")' + '?id=' + id + '&sourceId=' + sourceId,
                success: function (partialView) {
                    $('#modal-content').empty().html(partialView);
                    $('#submitBtn').click();
            },
            error: function(err){
                console.log(err);
            }
            });
        }

        function removeRelation(id) {
            $.ajax({
                method: 'POST',
                data: null,
                url: '@Url.Action("RemoveRelation", "Relation")' + '?id=' + id,
                success: function (response) {
                    if(response && response.IsRemoved)
                    {
                        window.location.href = window.location.href;
                    }
                },
                error: function (err){
                    console.log(err);
                }
            });
        }
</script>
}

ASPFamilyRelations/Views/Home/Index.cshtml
@model IEnumerable<DataAccess.Entities.Person>

@{
    ViewBag.Title = "Родственники";
}


<h3>База данных: родственники</h3>

@if (Model.Count() != 0)
{
<table class="table table-bordered table-hover">
    <tr>
        <th>№</th>
        <th>Фамилия</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Дата рождения</th>
        <th>Страна</th>
        <th>Город</th>
        <th>Улица</th>
        <th>Действие</th>
    </tr>
    @foreach (var line in Model)
    {
        <tr>
            <td>@line.Id</td>
            <td>@line.Surname</td>
            <td>@line.Name</td>
            <td>@line.Patronymic</td>
            <td>@line.BirthDate.Value.ToShortDateString()</td>
            <td>@line.Country</td>
            <td>@line.City</td>
            <td>@line.Street</td>
            <td>
                <button class="btn btn-xs btn-warning" title="Смотреть родственников" onclick="location.href='@Url.Action("GetRelations", "Home", new { id = line.Id })';return false;">
                    <i class="glyphicon glyphicon-zoom-in"></i>
                </button>
                <button class="btn btn-xs btn-warning" title="Редактировать человека" onclick="showPersonModal(@line.Id)">
                    <i class="glyphicon glyphicon-pencil"></i>
                </button>
                <button class="btn btn-xs btn-danger" title="Удалить человека" onclick="removePerson(@line.Id)">
                    <i class="glyphicon glyphicon-remove"></i>
                </button>
            </td>

        </tr>
    }
    <tr>
        <td></td>
        <td>@Html.DropDownList("Surname",
                               new string[] { " " }.Concat(Model.Select(x=>x.Surname)).Distinct()
                               .Select((e, i) => new SelectListItem
                               {
                                   Value = i.ToString(), Text = e
                               }), new { @class = "form-control", id = "surnames" })
        </td>
        <td>
            @Html.DropDownList("Name",
                            new string[] { " " }.Concat(Model.Select(x => x.Name)).Distinct()
                            .Select((e, i) => new SelectListItem
                            {
                                Value = i.ToString(),
                                Text = e
                            }), new { @class = "form-control", id = "names" })
        </td>
        <td>
            @Html.DropDownList("Patronymic",
                         new string[] { " " }.Concat(Model.Select(x => x.Patronymic)).Distinct()
                         .Select((e, i) => new SelectListItem
                         {
                             Value = i.ToString(),
                             Text = e
                         }), new { @class = "form-control", id = "patronymics" })
        </td>
        <td>
            @Html.DropDownList("Date",
                         new string[] { " " }.Concat(Model.Select(x => x.BirthDate.Value.ToShortDateString())).Distinct()
                         .Select((e, i) => new SelectListItem
                         {
                             Value = i.ToString(),
                             Text = e
                         }), new { @class = "form-control", id = "dates" })
        </td>
        <td>
            @Html.DropDownList("Country",
                         new string[] { " " }.Concat(Model.Select(x => x.Country)).Distinct()
                         .Select((e, i) => new SelectListItem
                         {
                             Value = i.ToString(),
                             Text = e
                         }), new { @class = "form-control", id = "countries" })
        </td>
        <td>
            @Html.DropDownList("City",
                         new string[] { " " }.Concat(Model.Select(x => x.City)).Distinct()
                         .Select((e, i) => new SelectListItem
                         {
                             Value = i.ToString(),
                             Text = e
                         }), new { @class = "form-control", id = "cities" })
        </td>
        <td>
            @Html.DropDownList("Street",
                         new string[] { " " }.Concat(Model.Select(x => x.Street)).Distinct()
                         .Select((e, i) => new SelectListItem
                         {
                             Value = i.ToString(),
                             Text = e
                         }), new { @class = "form-control", id = "streets" })
        </td>
        <td></td>
    </tr>
</table>
}
else
{
    <h4>База данных пуста</h4>
}


<button class="btn btn-default" title="Добавить человека" onclick="showPersonModal(0)">
    <i class="glyphicon glyphicon-plus"></i>
</button>
<button class="btn btn-default" title="Фильтровать людей" onclick="showFiltered()">
    <i class="glyphicon glyphicon-filter"></i>
</button>

<button class="hidden" id="submitBtn" data-toggle="modal" data-target="#myModal"></button>
<div id="modal-content">
</div>

@section Scripts{
<script type="text/javascript">
        function showPersonModal(id) {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("Edit")' + '?id=' + id,
                success: function (partialView) {
                    $('#modal-content').empty().html(partialView);
                    $('#submitBtn').click();
            },
            error: function(err){
                console.log(err);
            }
            });
        }

        function showFiltered() {
            var s = '?surname=' + $('#surnames option:selected').text();
            var n = '&name=' + $('#names option:selected').text();
            var p = '&patronymic=' + $('#patronymics option:selected').text();
            var b = '&birthDate=' + $('#dates option:selected').text();
            var co = '&country=' + $('#countries option:selected').text();
            var ci = '&city=' + $('#cities option:selected').text();
            var st = '&street=' + $('#streets option:selected').text();
            var result = s + n + p + b + co + ci + st;
            console.log($('#surnames').val());
            location.href = '@Url.Action("ShowFiltered", "Home")' + result;
            return false;

        }

        function removePerson(id) {
            $.ajax({
                method: 'POST',
                data: null,
                url: '@Url.Action("RemovePerson")' + '?id=' + id,
                success: function (response) {
                    if(response && response.IsRemoved)
                    {
                        window.location.href = window.location.href;
                    }
                },
                error: function(){
                    console.log(err);
                },
            });
}
</script>


}

ASPFamilyRelations/Views/Home/Modal/_Edit.cshtml
@model int


<!-- Modal -->
@using (Ajax.BeginForm((Model != 0 ? "UpdatePerson" : "AddPerson"), "Home", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "refresh" }))
{
    <div>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            @(Model != 0 ? (ViewBag.Details ? "Карточка родственника" : $"Редактирование человека с Id ={Model}") 
                                            : "Добавление нового человека")
                        </h4>
                    </div>
                    <div class="modal-body" id="refresh">
                        @Html.Action(ViewBag.Details ? "GetPersonDetails" : "GetPerson", "Home", new { id = Model})
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn @(ViewBag.Details ? "hidden" : "btn-primary")" value="Сохранить" />
                        <button type="button" class="btn btn-danger" data-dismiss="modal" id="closeBtn">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('#closeBtn').click(function () {
            window.location.href = window.location.href;
        });

    })
</script>

ASPFamilyRelations/Views/Home/Modal/_PersonDetailsPartial.cshtml
@model DataAccess.Entities.Person

@foreach (var prop in ViewData.ModelMetadata.Properties.OrderBy(x => x.DisplayName))
{
    if (prop.PropertyName != "Id")
    {
        <div class="form-group">
            <label>@prop.DisplayName: </label>
                @Html.Display(prop.PropertyName, null, new { @class = "form-control" })
        </div>
    }
}

ASPFamilyRelations/Views/Home/Modal/_PersonPartial.cshtml
@model DataAccess.Entities.Person
@using System.Globalization;

@if (ViewBag.Message != null)
{
    <div class="alert alert-success">@ViewBag.Message</div>
}

@Html.HiddenFor(m => m.Id)
@foreach (var prop in ViewData.ModelMetadata.Properties.OrderBy(x => x.DisplayName))
{
    if (prop.PropertyName != "Id")
    {
        <div class="form-group">
            <label>@prop.DisplayName</label>
            @if (prop.PropertyName == "BirthDate")
            {
                DateTime dt = Model?.BirthDate ?? DateTime.Now;
                DateTimeFormatInfo dtfi = CultureInfo.CreateSpecificCulture("en-US").DateTimeFormat;
                dtfi.DateSeparator = "-";
                dtfi.ShortDatePattern = @"yyyy/MM/dd";
                @Html.TextBox("BirthDate", String.Format("{0:d}", dt.ToString("d", dtfi)), new { @class = "datefield form-control", type = "date" })

            }
            else
            {
                @Html.TextBox(prop.PropertyName, null, new { @class = "form-control" })
            }
            @Html.ValidationMessage(prop.PropertyName)
        </div>
    }
}

ASPFamilyRelations/Views/Relation/Modal/_Edit.cshtml
@model int


<!-- Modal -->
@using (Ajax.BeginForm((Model != 0 ? "UpdateRelation" : "AddRelation"), "Relation", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "refresh" }))
{
    <div>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            @(Model != 0 ? $"Редактирование родства человека" : "Добавление нового родства")
                        </h4>
                    </div>
                    <div class="modal-body" id="refresh">
                        @if (Model != 0)
                        {
                            @Html.Action("GetRelation", "Relation", new { id = Model })
                        }
                        else
                        {
                            @Html.Action("NewRelation", "Relation", new { sourceId = ViewBag.SourceId })
                        }
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Сохранить" />
                        <button type="button" class="btn btn-danger" data-dismiss="modal" id="closeBtn">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('#closeBtn').click(function () {
            window.location.href = window.location.href;
        });

    })
</script>

ASPFamilyRelations/Views/Relation/Modal/_NewRelationPartial.cshtml
@model DataAccess.Entities.Relation
@using DataAccess.Entities

@if (ViewBag.Message != null)
{
    <div class="alert alert-success">@ViewBag.Message</div>
}

@Html.HiddenFor(m => m.Id)
@Html.HiddenFor(m => m.TargetPerson)
@Html.HiddenFor(m => m.SourceId)


<p>Человек:</p>
<label>@ViewBag.Person</label>
<p>является кем:</p>
@Html.DropDownListFor(x => x.RelationNameId, (ViewBag.RelationNames as IEnumerable<string>)
                          .Select((e, i) => new SelectListItem { Value = (i + 1).ToString(), Text = e }),
                          new { @class = "form-control" })
<br>
<p>для человека</p>
@Html.DropDownListFor(x => x.TargetId, (ViewBag.Persons as Person[])
                          .Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.ToString() }),
                          new { @class = "form-control" })

ASPFamilyRelations/Views/Relation/Modal/_RelationPartial.cshtml
@model DataAccess.Entities.Relation

@if (ViewBag.Message != null)
{
    <div class="alert alert-success">@ViewBag.Message</div>
}

@Html.HiddenFor(m => m.Id)
@Html.HiddenFor(m => m.TargetPerson)
@Html.HiddenFor(m => m.SourceId)
@Html.HiddenFor(m => m.TargetId)

<p>Человек:</p>
<label>@ViewBag.Person</label>
<p>является кем:</p>
@Html.DropDownListFor(x => x.RelationNameId, (ViewBag.RelationNames as IEnumerable<string>)
                          .Select((e, i) => new SelectListItem { Value = (i + 1).ToString(), Text = e }),
                          new { @class = "form-control" })
<br>
<p>для человека</p>
<label>@Model.TargetPerson.ToString()</label>

ASPFamilyRelations/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right" id="loginState">
                    
                        
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="my-content">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Family relations. Know your relations</p>
        </footer>
    </div>





    <script type="text/javascript">
    function showAdminPanel() {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("Index", "Admin")',
                success: function (view) {
                    $('.my-content').empty().html(view);
            },
                error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
            });
        }

        function showGuestPanel() {
            $.ajax({
                method: 'GET',
                data: null,
                url: '@Url.Action("ShowContent", "Home")',
                success: function (view) {
                    $('.my-content').empty().html(view);
            },
                error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
            });
        }


        function getLoginState() {
        $.ajax({
            method: 'GET',
            data: null,
            url: '@Url.Action("GetLoginState", "Login")',
            success: function (view) {
                console.log('SUCCESS');
                $('#loginState').empty().html(view);
            },
            error: function (err) {
                console.log('ERROR');
                console.log(err);
            }
        });
    }
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>